route:
  group_by: ['alertname', 'job']

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  receiver: discord
 
receivers:
- name: discord
  discord_configs:
  - webhook_url: https://discord.com/api/webhooks/1349713415530217482/O758aL5RthrI_CG5ve-dQjHRasaTWEMSS-rG337FvAxHm0aZ_1isEunHZ34lbWV8nuL1
    send_resolved: true