apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: monitoring-yolo
  namespace: model
  labels:
    monitorName: yolo
  annotations:
    serving.kserve.io/enable-metric-aggregation: "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
    prometheus.kserve.io/port: '8080'
    prometheus.kserve.io/path: "/metrics"
spec:
  predictor:
    serviceAccountName: sa
    containers:
      - name: kserve-container
        image: silit/monitoring:v1
        env: 
        - name: STORAGE_URI
          value: s3://cifar-torch/